name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install tox
    - name: lint/pre-commit
      run: |
        tox -e pre-commit
    - name: Tests
      run: |
        tox -e py37
